// <auto-generated />
using FoodStop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodStop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240111034717_BranchSeeding")]
    partial class BranchSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodStop.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Location = "covai",
                            Name = "A2B Restraurant",
                            PhoneNo = 1234567890L
                        },
                        new
                        {
                            Id = 6,
                            Location = "covai",
                            Name = "Covai Koli Restraurant",
                            PhoneNo = 1234567890L
                        },
                        new
                        {
                            Id = 7,
                            Location = "SAP",
                            Name = "Gowtham Restraurant",
                            PhoneNo = 1234567890L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
